import {
  Activity,
  Bot,
  Boxes,
  Braces,
  CalendarClock,
  CheckCheck,
  Cpu,
  Database,
  FileBox,
  FileCheck2,
  Fingerprint,
  GitBranch,
  Layers3,
  LayoutDashboard,
  Library,
  ListVideo,
  Monitor,
  Network,
  Route,
  Settings2,
  ShieldCheck,
  Terminal,
  Users,
  Workflow,
} from "lucide-react";

export const sections = [
  { label: "Command Center", slug: "", icon: LayoutDashboard, group: "WORKSPACE" },
  { label: "Workbench", slug: "workbench", icon: Workflow, group: "WORKSPACE" },
  { label: "Agents", slug: "agents", icon: Bot, group: "BUILD" },
  { label: "Teams", slug: "teams", icon: Users, group: "BUILD" },
  { label: "Graphs", slug: "graphs", icon: GitBranch, group: "BUILD" },
  { label: "Models & Providers", slug: "models", icon: Cpu, group: "CONNECT" },
  { label: "Router", slug: "router", icon: Route, group: "CONNECT" },
  { label: "Tools & MCP", slug: "tools", icon: Terminal, group: "CONNECT" },
  { label: "Knowledge", slug: "knowledge", icon: Library, group: "CONTEXT" },
  { label: "Memory", slug: "memory", icon: Database, group: "CONTEXT" },
  { label: "Runs", slug: "runs", icon: ListVideo, group: "OPERATE" },
  { label: "Approvals", slug: "approvals", icon: ShieldCheck, group: "OPERATE" },
  { label: "Schedules", slug: "schedules", icon: CalendarClock, group: "OPERATE" },
  { label: "Artifacts", slug: "artifacts", icon: FileBox, group: "VERIFY" },
  { label: "Evidence", slug: "evidence", icon: Fingerprint, group: "VERIFY" },
  { label: "Evaluations", slug: "evaluations", icon: CheckCheck, group: "VERIFY" },
  { label: "Observability", slug: "observability", icon: Activity, group: "VERIFY" },
  { label: "Policies & Permissions", slug: "policies", icon: FileCheck2, group: "GOVERN" },
  { label: "Devices", slug: "devices", icon: Monitor, group: "GOVERN" },
  { label: "Architecture Map", slug: "architecture", icon: Network, group: "SYSTEM" },
  { label: "Settings", slug: "settings", icon: Settings2, group: "SYSTEM" },
];
export const agents = [
  {
    name: "Research Analyst",
    initials: "RA",
    description: "Deep research, grounded in evidence.",
    model: "Claude Sonnet 4.5",
    tools: 6,
    runs: 1248,
    status: "Active",
    color: "blue",
    icon: Bot,
  },
  {
    name: "Code Engineer",
    initials: "CE",
    description: "From specification to production code.",
    model: "GPT-5",
    tools: 8,
    runs: 864,
    status: "Active",
    color: "violet",
    icon: Braces,
  },
  {
    name: "Data Specialist",
    initials: "DS",
    description: "Turn complex data into clear decisions.",
    model: "Gemini 2.5 Pro",
    tools: 5,
    runs: 612,
    status: "Active",
    color: "cyan",
    icon: Database,
  },
  {
    name: "Quality Reviewer",
    initials: "QR",
    description: "Independent checks. Reliable outcomes.",
    model: "Claude Sonnet 4.5",
    tools: 4,
    runs: 436,
    status: "Idle",
    color: "amber",
    icon: ShieldCheck,
  },
  {
    name: "Operations Lead",
    initials: "OL",
    description: "Coordinate teams and resolve blockers.",
    model: "GPT-5",
    tools: 7,
    runs: 328,
    status: "Active",
    color: "green",
    icon: Boxes,
  },
  {
    name: "Knowledge Curator",
    initials: "KC",
    description: "Keep institutional context up to date.",
    model: "Gemini 2.5 Flash",
    tools: 3,
    runs: 208,
    status: "Idle",
    color: "cyan",
    icon: Layers3,
  },
];
export type Run = {
  id: string;
  name: string;
  agent: string;
  status: string;
  time: string;
  tokens: string;
  cost: string;
  progress: number;
};
export const initialRuns: Run[] = [
  {
    id: "run_8f2a",
    name: "Competitive landscape analysis",
    agent: "Research Analyst",
    status: "Running",
    time: "2m 34s",
    tokens: "18.4k",
    cost: "$0.124",
    progress: 68,
  },
  {
    id: "run_7e1b",
    name: "Review authentication PR #248",
    agent: "Code Engineer",
    status: "Needs approval",
    time: "4m 12s",
    tokens: "24.1k",
    cost: "$0.186",
    progress: 85,
  },
  {
    id: "run_6d9c",
    name: "Weekly revenue reconciliation",
    agent: "Data Specialist",
    status: "Completed",
    time: "1m 48s",
    tokens: "12.6k",
    cost: "$0.082",
    progress: 100,
  },
  {
    id: "run_5c8d",
    name: "Sync product knowledge base",
    agent: "Knowledge Curator",
    status: "Completed",
    time: "56s",
    tokens: "8.2k",
    cost: "$0.034",
    progress: 100,
  },
  {
    id: "run_4b7e",
    name: "Generate release notes v2.8",
    agent: "Code Engineer",
    status: "Completed",
    time: "2m 16s",
    tokens: "16.8k",
    cost: "$0.112",
    progress: 100,
  },
  {
    id: "run_3a6f",
    name: "Validate customer export",
    agent: "Quality Reviewer",
    status: "Failed",
    time: "32s",
    tokens: "3.1k",
    cost: "$0.018",
    progress: 32,
  },
];
export const initialApprovals = [
  {
    id: "apr_01",
    title: "Merge authentication changes",
    agent: "Code Engineer",
    action: "github.merge_pull_request",
    detail: "Pull request #248 · praxis/platform",
    risk: "High",
    age: "4 min ago",
  },
  {
    id: "apr_02",
    title: "Publish market research report",
    agent: "Research Analyst",
    action: "notion.publish_page",
    detail: "External workspace · Strategy / Q4",
    risk: "Medium",
    age: "12 min ago",
  },
  {
    id: "apr_03",
    title: "Export customer dataset",
    agent: "Data Specialist",
    action: "storage.write_file",
    detail: "1,284 records · PII masking enabled",
    risk: "High",
    age: "18 min ago",
  },
];
export const catalog: Record<string, { columns: string[]; rows: string[][]; description: string }> =
  {
    teams: {
      description: "Specialists working together. One shared objective.",
      columns: ["Team", "Members", "Orchestration", "Active runs", "Status"],
      rows: [
        ["Product Intelligence", "4 agents", "Supervisor", "3", "Active"],
        ["Engineering", "3 agents", "Sequential", "2", "Active"],
        ["Revenue Operations", "3 agents", "Parallel", "1", "Active"],
        ["Content Studio", "2 agents", "Supervisor", "0", "Idle"],
      ],
    },
    models: {
      description: "A unified model layer. The right intelligence for every task.",
      columns: ["Model", "Provider", "Context", "Input / 1M", "Latency", "Status"],
      rows: [
        ["Claude Sonnet 4.5", "Anthropic", "200k", "$3.00", "840 ms", "Healthy"],
        ["GPT-5", "OpenAI", "400k", "$1.25", "720 ms", "Healthy"],
        ["Gemini 2.5 Pro", "Google", "1M", "$1.25", "680 ms", "Healthy"],
        ["Gemini 2.5 Flash", "Google", "1M", "$0.30", "320 ms", "Healthy"],
        ["DeepSeek V3.1", "DeepSeek", "128k", "$0.56", "920 ms", "Healthy"],
        ["Llama 4 Maverick", "Local / Ollama", "128k", "$0.00", "210 ms", "Offline"],
      ],
    },
    memory: {
      description: "Persistent context with explicit boundaries and provenance.",
      columns: ["Memory", "Scope", "Type", "Entries", "Updated", "Status"],
      rows: [
        ["Product intelligence", "Team", "Episodic", "248", "2 min ago", "Active"],
        ["Engineering conventions", "Workspace", "Semantic", "86", "18 min ago", "Active"],
        ["Research scratchpad", "Run", "Working", "12", "Just now", "Active"],
        ["Customer preferences", "Agent", "Semantic", "162", "1 hr ago", "Active"],
      ],
    },
    schedules: {
      description: "Reliable autonomous work, on your schedule.",
      columns: ["Schedule", "Agent / Graph", "Frequency", "Next run", "Timezone", "Status"],
      rows: [
        [
          "Morning intelligence brief",
          "Research Analyst",
          "Every weekday · 08:00",
          "Tomorrow, 08:00",
          "UTC",
          "Active",
        ],
        [
          "Revenue reconciliation",
          "Revenue Operations",
          "Monday · 09:00",
          "Oct 12, 09:00",
          "UTC",
          "Active",
        ],
        ["Knowledge sync", "Knowledge Curator", "Every 6 hours", "Today, 12:00", "UTC", "Active"],
        ["Dependency audit", "Code Engineer", "Friday · 17:00", "Oct 9, 17:00", "UTC", "Paused"],
      ],
    },
    artifacts: {
      description: "The tangible outputs of autonomous work.",
      columns: ["Artifact", "Format", "Created by", "Size", "Created", "Status"],
      rows: [
        [
          "competitive-landscape-q4.pdf",
          "PDF",
          "Research Analyst",
          "2.4 MB",
          "12 min ago",
          "Verified",
        ],
        ["revenue-week-40.csv", "CSV", "Data Specialist", "184 KB", "28 min ago", "Verified"],
        ["release-notes-v2.8.md", "Markdown", "Code Engineer", "12 KB", "42 min ago", "Verified"],
        ["auth-review-248.json", "JSON", "Quality Reviewer", "32 KB", "1 hr ago", "Pending"],
      ],
    },
    evaluations: {
      description: "Measure quality, not just completion.",
      columns: ["Evaluation suite", "Dataset", "Pass rate", "Last run", "Evaluator", "Status"],
      rows: [
        [
          "Research groundedness",
          "120 cases",
          "98.2%",
          "Today, 09:42",
          "LLM + assertions",
          "Passed",
        ],
        ["Code correctness", "84 cases", "96.4%", "Today, 08:30", "Unit tests", "Passed"],
        ["Policy adherence", "200 cases", "100%", "Today, 08:15", "Deterministic", "Passed"],
        ["Tool selection accuracy", "64 cases", "92.1%", "Yesterday", "LLM judge", "Needs review"],
      ],
    },
    policies: {
      description: "Clear guardrails. Accountable autonomy.",
      columns: ["Policy", "Scope", "Rule", "Enforcement", "Updated", "Status"],
      rows: [
        [
          "External write approval",
          "Workspace",
          "Require human approval",
          "Blocking",
          "Oct 6",
          "Active",
        ],
        [
          "PII protection",
          "All agents",
          "Mask personal information",
          "Blocking",
          "Oct 5",
          "Active",
        ],
        ["Run budget limit", "Workspace", "Maximum $5.00 per run", "Blocking", "Oct 4", "Active"],
        [
          "Model allowlist",
          "Engineering",
          "Approved providers only",
          "Blocking",
          "Oct 3",
          "Active",
        ],
        [
          "Evidence requirement",
          "Research",
          "Cite source for every claim",
          "Advisory",
          "Oct 2",
          "Active",
        ],
      ],
    },
    devices: {
      description: "The endpoints where your agents work.",
      columns: ["Device", "Runtime", "Location", "Last seen", "Capabilities", "Status"],
      rows: [
        [
          "praxis-worker-01",
          "Cloud sandbox",
          "EU West",
          "Just now",
          "Browser, Python, Node",
          "Online",
        ],
        ["praxis-worker-02", "Cloud sandbox", "US East", "12 sec ago", "Browser, Python", "Online"],
        [
          "MacBook Pro · Ricardo",
          "Local companion",
          "Local",
          "2 min ago",
          "Filesystem, Shell",
          "Online",
        ],
        ["staging-worker", "Docker container", "EU West", "2 hrs ago", "Node, Git", "Offline"],
      ],
    },
  };