import { agents, catalog, initialApprovals, initialRuns, type Run } from './data';
export type Agent = (typeof agents)[number] & { role?: string; goal?: string; memory?: string; knowledge?: string; permissions?: string; success?: string; toolNames?: string[]; level?: number };
export type ResourceKind = 'teams'|'providers'|'tools'|'knowledge'|'memory'|'schedules'|'artifacts'|'evidence'|'evaluations'|'policies'|'devices'|'projects';
export type Resource = { id:string; name:string; type:string; status:string; scope:string; description:string; updated:string; confidence:number; provenance:string; fields:Record<string,string>; content:string };
export type GraphNode = { id:string; name:string; type:string; purpose:string; x:number; y:number; model:string; tool:string; inputs:string; outputs:string; permissions:string; limit:string; status:string };
export type GraphEdge = { id:string; from:string; to:string };
export type Graph = { id:string; name:string; version:number; pattern:string; nodes:GraphNode[]; edges:GraphEdge[] };
export type Event = { id:string; time:string; subject:string; message:string; level:'INFO'|'WARN'|'ERROR' };
export type ApprovalDecision = { id:string; title:string; status:string; at:string };
export type Message = { id:string; project:string; author:string; text:string; time:string };
export type MockState = { agents:Agent[]; graphs:Graph[]; runs:Run[]; approvals:typeof initialApprovals; decisions:ApprovalDecision[]; resources:Record<ResourceKind,Resource[]>; events:Event[]; messages:Message[]; permissions:Record<string,boolean>; preferences:Record<string,string|boolean>; ui:Record<string,unknown> };
export const resourceKinds:ResourceKind[]=['teams','providers','tools','knowledge','memory','schedules','artifacts','evidence','evaluations','policies','devices','projects'];
export const memoryTypes=['Working','Conversation','Semantic','Episodic','Procedural','Entity/Relationship','Task','Agent','Shared Team','Long-term User','Checkpoint'];
export const nodeGroups:Record<string,string[]>={ 'Entry & intent':['Trigger','Input'], 'Intelligence':['Agent','Model','Router','Supervisor','Handoff'], 'Actions':['Tool','MCP','Search','Browser','Computer','Code','Python'], 'Context':['Knowledge','Memory Read','Memory Write'], 'Control flow':['Condition','Switch','Parallel','Loop','Retry','Delay'], 'Governance':['Policy','Human Approval','Evaluator','Guardrail','Checkpoint'], 'Products':['Artifact','Evidence','Output'] };
const names=['Trigger','Policy','Router','Research Agent','Search','Knowledge','Evidence','Reviewer','Artifact','Output'];
export function createDemoGraph():Graph {const nodes=names.map((name,i)=>({id:`node_${i}`,name,type:name==='Research Agent'||name==='Reviewer'?'Agent':name,purpose:name==='Reviewer'?'Critique claims and verify citations':`Process ${name.toLowerCase()} with a verifiable handoff`,x:42+(i%5)*212,y:i<5?126:340,model:name==='Router'?'Policy-aware routing':'Claude Sonnet 4.5',tool:name==='Search'?'web.search':name==='Knowledge'?'knowledge.retrieve':'none',inputs:i===0?'task: string':'context: object',outputs:name==='Output'?'report: artifact':'result: object',permissions:['Search','Artifact'].includes(name)?'REVIEW external writes':'ALLOW workspace read',limit:'$0.50 · 30s · 8k tokens',status:'Ready'}));return {id:'graph_research',name:'Research & synthesis',version:4,pattern:'Verification',nodes,edges:nodes.slice(1).map((n,i)=>({id:`edge_${i}`,from:nodes[i]?.id??'node_0',to:n.id}))};}
function resource(kind:ResourceKind,name:string,type:string,fields:Record<string,string>,i=0):Resource{return {id:`${kind}_${i}`,name,type,status:kind==='devices'?'Unpaired':kind==='evaluations'?'Passed':kind==='artifacts'||kind==='evidence'?'Verified':'Active',scope:'Workspace',description:`${name} · scoped, governed and simulated in PRAXIS.`,updated:'2026-10-08 03:40 UTC',confidence:.98,provenance:kind==='memory'?'run_6d9c / research checkpoint':'seed / Acme workspace',fields,content:kind==='knowledge'?'PRAXIS provides a governed operating layer for autonomous work. Every task is scoped by policy, enriched with institutional knowledge, and verified against primary evidence. External actions require review; outputs include citations, provenance, cost and quality measurements.':`# ${name}\n\nSIMULATED OUTPUT · PRAXIS\n\nSources collected and validated. All claims have supporting evidence. Quality threshold: 0.95. Final confidence: 0.982.\n\nNo external services were contacted.`};}
export function createInitialState():MockState {
 const resources=Object.fromEntries(resourceKinds.map(k=>[k,[]])) as Record<ResourceKind,Resource[]>;
 resources.teams=['Product Intelligence','Engineering','Revenue Operations','Content Studio'].map((n,i)=>resource('teams',n,['Supervisor','Sequential','Parallel','Supervisor'][i]??'Supervisor',{department:i===1?'Engineering':'Operations',members:agents.slice(i,i+3).map(a=>a.name).join(', '),objective:i===0?'Evidence-backed product decisions':'Reliable weekly delivery',dependencies:i===0?'Knowledge Curator → Research Analyst → Quality Reviewer':'Operations Lead → specialists',products:'Reports · evidence bundles',budget:'$25 / day'},i));
 resources.providers=['Anthropic','OpenAI','Google','DeepSeek','Local / Ollama'].map((n,i)=>resource('providers',n,i===4?'Local':'Cloud',{credential:'not configured',health:i===4?'Offline':'Healthy (simulated)',rpm:String(60+i*30),tpm:'120000',dailyBudget:'25',fallback:i===0?'GPT-5 → Gemini 2.5 Flash':'Claude Sonnet 4.5 → Gemini 2.5 Flash',region:'EU West',models:(catalog.models?.rows??[]).filter(r=>r[1]===n).map(r=>r[0]).join(', ')},i));
 resources.tools=['GitHub MCP','Browser runtime','Python sandbox','Notion MCP','Filesystem','Slack MCP','Moodle adapter','Drive adapter','IoT simulator'].map((n,i)=>resource('tools',n,i===1?'Browser':i===2?'Code':i===4?'Filesystem':i===8?'IoT':'MCP',{contract:i===0?'github.read_repository':i===2?'python.execute':i===8?'device.read_telemetry':'workspace.search',inputs:'query: string, limit: integer',outputs:'items: array, evidence: object',permission:i===0||i===3?'REVIEW external write':'ALLOW sandbox read',limit:'30 calls/min · 10s timeout',dependencies:i===0?'Git provider (mock)':i===8?'Virtual sensor (mock)':'Isolated sandbox',credential:'not configured',lastTest:'Never',result:'Awaiting sandbox test'},i));
 resources.knowledge=['PRAXIS product strategy','Engineering handbook','Q4 competitive intelligence','API & integration reference'].map((n,i)=>resource('knowledge',n,i%2?'PDF':'Markdown',{collection:i===1?'Engineering':'Product intelligence',stage:'Evidence',parser:i%2?'PDF text parser':'Markdown parser',chunks:String([42,128,86,64][i]??42),freshness:i===2?'Stale · 7 days':'Fresh · 2 hours',retention:'90 days',citation:`[src_${i}:§2]`,retrieval:'semantic + keyword · top 8'},i));
 resources.memory=memoryTypes.map((n,i)=>resource('memory',`${n} context`,n,{retention:i===0?'Run lifetime':i===10?'30 days':'90 days',entries:String(12+i*17),access:i>=8?'Team':'Agent',confidence:(.9+i*.007).toFixed(3),source:i===2?'Knowledge: Engineering handbook':`run_6d9c / step ${i+1}`},i));
 resources.schedules=['Morning intelligence brief','Knowledge sync','Inbound event digest','Policy exception watcher','Revenue threshold check'].map((n,i)=>resource('schedules',n,['Cron','Interval','Webhook','Event','Conditional'][i]??'Cron',{expression:['0 8 * * 1-5','Every 6 hours','mock://events/research','artifact.created','revenue.delta > 10%'][i]??'',next:i===2||i===3?'Awaiting simulated event':'2026-10-09 08:00 UTC',concurrency:'2',budget:'5',retries:'3',backoff:'Exponential · 2s',agent:agents[i]?.name??'Research Analyst'},i));
 resources.artifacts=['competitive-landscape-q4.pdf','revenue-week-40.csv','release-notes-v2.8.md','auth-review-248.json','routing-policy.py','architecture-preview.svg','research-evidence.bundle'].map((n,i)=>resource('artifacts',n,['PDF','Dataset','Report','JSON','Code','Image','Evidence bundle'][i]??'File',{version:`1.${i}`,run:['run_8f2a','run_6d9c','run_4b7e'][i%3]??'run_6d9c',author:agents[i%6]?.name??'Research Analyst',size:`${12+i*34} KB`,sources:'6 verified primary sources',classification:'Internal',mime:i===5?'image/svg+xml':'text/plain'},i));
 resources.evidence=['Competitive landscape evidence','Revenue reconciliation evidence','Authentication review evidence'].map((n,i)=>resource('evidence',n,'Evidence bundle',{run:initialRuns[i]?.id??'run_6d9c',claims:'24',sources:'6',grounding:'98.2%',integrity:'SIMULATED verification',artifact:resources.artifacts[i]?.name??'report'},i));
 resources.evaluations=['Grounding regression','Tool selection','Routing quality','Policy adherence','Cost guardrails','Latency budget','Code correctness'].map((n,i)=>resource('evaluations',n,['Grounding','Tools','Routing','Policy','Cost','Latency','Regression'][i]??'Regression',{dataset:`dataset_${i} · ${40+i*12} cases`,passRate:i===1?'92.1%':'98.2%',threshold:'0.95',regressions:i===1?'3':'0',cost:'$0.032',latency:'720ms',lastRun:'2026-10-08 03:30 UTC',cases:'Primary-source citation | Correct tool | Budget compliance'},i));
 resources.policies=['Workspace reads','External write approval','Restricted data export','Run budget limit','Evidence requirement'].map((n,i)=>resource('policies',n,['ALLOW','REVIEW','DENY','REVIEW','ALLOW'][i]??'REVIEW',{rule:['resource.scope == workspace','action.type == external_write','data.classification == restricted','run.cost > budget','output.grounding >= 0.95'][i]??'',engine:i<2?'RBAC':'ABAC',roles:i===0?'Owner, Operator, Builder, Viewer':'Owner, Operator',classification:i===2?'Restricted':'Internal',threshold:i===3?'$5.00':'0.95 confidence',budget:'5',resource:i===1?'Tool → external workspace':'Agent → Knowledge → Artifact',scope:'workspace/*'},i));
 resources.devices=['Ricardo workstation','Mobile companion','Browser session','Cloud sandbox','IoT test sensor'].map((n,i)=>resource('devices',n,['PC','Mobile','Browser','Sandbox','IoT'][i]??'PC',{capabilities:['Filesystem, shell','Notifications, approvals','Web browsing, capture','Python, Node, isolation','Temperature, telemetry'][i]??'',lastSeen:'Never · unpaired',pairing:'Not configured',transport:'Mock only',region:i===3?'EU West':'Local',permissions:'Read only'},i));
 resources.projects=['Q4 product intelligence','Platform reliability','Revenue operations'].map((n,i)=>resource('projects',n,'Project',{goal:['Map market opportunities','Improve policy coverage','Reconcile weekly datasets'][i]??'',team:resources.teams[i]?.name??'Engineering',graph:'Research & synthesis',deliverables:'Report + evidence',budget:'25'},i));
 return {agents:[...agents],graphs:[createDemoGraph()],runs:[...initialRuns],approvals:[...initialApprovals],decisions:[],resources,events:[{id:'evt_seed',time:'03:40:00',subject:'workspace',message:'MOCK runtime initialized. No external credentials configured.',level:'INFO'}],messages:[{id:'msg_seed',project:'projects_0',author:'Research Analyst',text:'Research scope prepared. Six primary-source categories and a reviewer checkpoint are ready for simulation.',time:'03:40'}],permissions:{},preferences:{workspace:'Acme workspace',timezone:'UTC',currency:'USD'},ui:{}};
}
export function advanceRuns(runs:Run[]):Run[]{return runs.map(r=>r.status==='Running'?{...r,progress:Math.min(100,r.progress+8),status:r.progress+8>=100?'Completed':'Running',tokens:`${(r.progress*.18).toFixed(1)}k`,cost:`$${(r.progress*.0012).toFixed(3)}`,time:r.time==='Just now'?'2s':r.time}:r);}
export function connectGraph(graph:Graph,from:string,to:string):Graph {if(from===to||!graph.nodes.some(n=>n.id===from)||!graph.nodes.some(n=>n.id===to)||graph.edges.some(e=>e.from===from&&e.to===to))return graph;return {...graph,edges:[...graph.edges,{id:`edge_${from}_${to}`,from,to}]};}
export function deleteGraphNode(graph:Graph,id:string):Graph{return {...graph,nodes:graph.nodes.filter(n=>n.id!==id),edges:graph.edges.filter(e=>e.from!==id&&e.to!==id)};}
export function exportMock(name:string,value:unknown){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}